version: '3.8'
services:
  user-service:
    image: onikaze/sample-app-docker-user:latest
    ports:
      - "5001:5001"
    volumes:
      - /home/ec2-user/log:/app/log
      - /home/ec2-user/db:/app/db
    networks:
      - microservices-network
    restart: unless-stopped

  post-service:
    image: onikaze/sample-app-docker-post:latest
    ports:
      - "5002:5002"
    volumes:
      - /home/ec2-user/log:/app/log
      - /home/ec2-user/db:/app/db
    networks:
      - microservices-network
    depends_on:
      - user-service
    restart: unless-stopped

  notification-service:
    image: onikaze/sample-app-docker-notification:latest
    ports:
      - "5003:5003"
    volumes:
      - /home/ec2-user/log:/app/log
      - /home/ec2-user/db:/app/db
    networks:
      - microservices-network
    depends_on:
      - user-service
      - post-service
    environment:
      EMAIL_SERVER_ADDRESS: smtp.gmail.com
      EMAIL_SERVER_FROM: xinguifeng3@gmail.com
      EMAIL_SERVER_KEY: ndfdezhukrftnqox
      EMAIL_SERVER_PORT: 587
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    networks:
      - microservices-network
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - microservices-network
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus 
    ports:
      - "9090:9090"
    networks:
      - microservices-network
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
      - alertmanager:alertmanager
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - microservices-network
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
