global:
  scrape_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5001']
        labels:
          container: 'user-service'

  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:5002']
        labels:
          container: 'post-service'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5003']
        labels:
          container: 'notification-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
